# Generated by Django 5.2.6 on 2025-09-08 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_chat_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token_limit',
            field=models.IntegerField(default=150),
        ),
        migrations.AddField(
            model_name='user',
            name='token_usage',
            field=models.IntegerField(default=0),
        ),
    ]
